"""create templates and document_records tables

Revision ID: 207a977bc32b
Revises: 4140d472bf11
Create Date: 2025-12-12 12:49:11.713620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207a977bc32b'
down_revision: Union[str, Sequence[str], None] = '4140d472bf11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('template_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_name', name='uq_user_template_name')
    )
    op.create_index(op.f('ix_templates_is_public'), 'templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_table('document_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('record_index', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_record_text', sa.Text(), nullable=True),
    sa.Column('parsing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'record_index', name='uq_doc_record_index')
    )
    op.create_index(op.f('ix_document_records_document_id'), 'document_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_records_record_id'), 'document_records', ['record_id'], unique=False)
    op.create_index(op.f('ix_document_records_template_id'), 'document_records', ['template_id'], unique=False)
    op.drop_index(op.f('ix_user_preferences_preference_key'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_constraint(op.f('sqlite_databases_storage_path_key'), 'sqlite_databases', type_='unique')
    op.drop_index(op.f('ix_sqlite_databases_storage_path'), table_name='sqlite_databases')
    op.create_index(op.f('ix_sqlite_databases_storage_path'), 'sqlite_databases', ['storage_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sqlite_databases_storage_path'), table_name='sqlite_databases')
    op.create_index(op.f('ix_sqlite_databases_storage_path'), 'sqlite_databases', ['storage_path'], unique=False)
    op.create_unique_constraint(op.f('sqlite_databases_storage_path_key'), 'sqlite_databases', ['storage_path'], postgresql_nulls_not_distinct=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preference_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preference_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey')),
    sa.UniqueConstraint('user_id', 'preference_key', name=op.f('uq_user_preference'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_preference_key'), 'user_preferences', ['preference_key'], unique=False)
    op.drop_index(op.f('ix_document_records_template_id'), table_name='document_records')
    op.drop_index(op.f('ix_document_records_record_id'), table_name='document_records')
    op.drop_index(op.f('ix_document_records_document_id'), table_name='document_records')
    op.drop_table('document_records')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_public'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
